### ISSUE TITLE
Update RStudio to Posit

### ISSUE THREAD

**Issue by gsingh91** [rstudio/spark.rstudio.com#145]
With RStudio now rebranded to Posit, we would need to update the documentation for Posit products, a few example pages that need updating:
https://spark.rstudio.com/deployment/databricks-cluster.html#using-rstudio-team-with-databricks
https://spark.rstudio.com/deployment/qubole-overview.html#using-rstudio-workbench-with-qubole

**Comment by edgararuiz** [comment]
Done
