### ISSUE TITLE
braindump re: updates to sparklyr website

### ISSUE THREAD

**Issue by kevinushey** [rstudio/spark.rstudio.com#16]
## Global

- [x] Should we consider replacing all instances of Spark 1.6.1 with Spark 2.0.0, given that this is now the latest stable release?

## ML

- [x] Mention formula interface (currently does not accept interaction terms). We might even want to use it in preference to setting `response =` and `features =` in the examples.
- [x] Mention `ml.options` argument as an 'experts-only' interface for tweaks to Spark model output. In particular, `model.transform` as an R function that can be used to mutate the Spark model object before the fit is performed.

## Extensions

- [x] Mention the `ensure_*` family of functions, and that they should be used by extensions to enforce types for parameters passed to invoke (e.g. Spark routines that require an `integer` will not accept an R `numeric` element).
- [x] Mention `spark_compilation_spec` for users who would like to take more control over where the `scalac` compilers should be looked up.
- [x] Use actual blockquote styling for CRAN guidelines re: included Java code.

## Miscellaneous

I feel like we need to mention more of the `sdf_` functions as a more direct interface to Spark DataFrames that lies outside of the `dplyr` interface, but I'm not sure what such a section should be called / what it should live. Maybe a sub-section of the `dplyr` page?

**Comment by slopp** [comment]
ML  - also touch on ml save / ml load? 

ML -  discuss what the ml_prepare_dataframe is doing, how categorical features are being handled automatically

+1 on miscellaneous

**Comment by nwstephens** [comment]
All suggestions have been implemented. Thank you for the feedback.
