### ISSUE TITLE
Broken link in `ml_generalized_linear_regression`?

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/spark.rstudio.com#49]
See: http://spark.rstudio.com/reference/sparklyr/latest/ml_generalized_linear_regression.html

Link to `glm` under `family` points to a broken link: http://www.inside-r.org/r-doc/stats/glm

Not sure if this is a temporary issue or something we have to fix.

**Comment by edgararuiz** [comment]
Updated the Reference section, the problem seems to have been resolved.
