### ISSUE TITLE
Should we list all config options and improve navigation?

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/spark.rstudio.com#63]
Some users have mentioned they wish they could change the `spark_install` location. This is already available with the `spark.install.dir` setting; however, this setting is under http://spark.rstudio.com/deployment.html which users wouldn't expect, I think.

Should we consider adding a `Settings` tab under `Reference` to list all configuration settings?

Should we also consider restructuring the navigation for the `sparklyr 0.6` release? Here are some the tab structure I would consider:

- Overview: Same as today's `Home`
- Guides: We could group here tabs for: Installation, Connection, dplyr, DBI, ML, Livy, etc?
- Deployment: We could create tabs for each deployment platform, as in: EC2, EMR, Cloudera, etc. rename `Deployment Examples` to `Guides`?
- Examples: Same as today.
- References: Same as today but would rename `Functions Reference` to `Functions`, add a `Settings` tab and rename `Additional Resources` to `Media`?

**Comment by edgararuiz** [comment]
Yeah, 0.6 is an opportunity to re-do the site.  I would also like to see if it makes sense to revamp it using blogdown now that I'm using it to build the db.rstudio.com site.

**Comment by jjallaire** [comment]
I'd be careful with blogdown for this site in particular. One *great*
feature of pkgdown is cross-linking of all functions within source code on
the site to the reference. I wouldn't give that up just for the gain in
attractiveness we'd get from blogdown (we'd also get the ability to
incorporate a blog for news, which would be very nice!). Perhaps there is a
way we could bring the pkgdown code formatting into blogdown...

**Comment by edgararuiz** [comment]
That's what I was thinking. My hope is that we can modify the R script we use to integrate pkgdown with RMarkdown Websites to integrate with blgodown instead.  From the time I've spent so far in blogdown I think it may be possible.  You're right, is not worth moving to a Hugo based site if we loose the automated reference, news and home page updates.  Thanks!
