### ISSUE TITLE
Links broken in mllib guide

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/spark.rstudio.com#65]
For example, on https://spark.rstudio.com/articles/guides-mllib.html

`kmeans` leads to https://spark.rstudio.com/articles/reference/sparklyr/latest/ml_kmeans.html

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>28F177843D99D452</RequestId>
<HostId>
Bvm+9crkwXsSPeJ5x085JrGhcTW5yhJJ2MKYgshhEnOI11E1xtNIU8ml1smkNprsJbMD5zkC6J8=
</HostId>
</Error>
```

**Comment by kevinykuo** [comment]
So currently the "good" link is https://spark.rstudio.com/reference/[function].html. @edgararuiz @javierluraschi how would you like to handle this?

**Comment by edgararuiz** [comment]
I'm not sure if there's an alternative to reviewing and correcting all articles manually

**Comment by kevinykuo** [comment]
@edgararuiz would it be OK if we assume the links on https://spark.rstudio.com/reference/index.html have the correct structure and change the rest of the site to follow?

More concretely, for the ML page we'd replace `"articles/reference/sparklyr/latest/"` with `"reference/"`.

**Comment by edgararuiz** [comment]
Yes, the Reference page should be our guide.
