### ISSUE TITLE
Google search results have incomplete title

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/spark.rstudio.com#74]
Google results look like:

<img width="620" alt="screen shot 2018-06-13 at 9 45 02 am" src="https://user-images.githubusercontent.com/3478847/41340151-99202e62-6eee-11e8-9524-315520a40c16.png">

The `<title>sparklyr</title>` should be changed to somethign like `<title>sparklyr: R interface for Apache Spark</title>`.

We should probably also add:

```html
<meta name="description" content="R interface to Apache Spark, a fast and general engine for big data processing. This package supports connecting to local and remote Apache Spark clusters, provides a dplyr compatible back-end, and provides an interface to Spark's built-in machine learning algorithms.">
<meta name="keywords" content="r,rstats,apache,spark,big data,package,cluster,dplyr,machine learning,ml">
```

Bonus points for adding a sitemap, [sitemaps.org](https://www.sitemaps.org/protocol.html), something like the following saved under `spark.rstudio.com/sitemap.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>http://spark.rstudio.com/dplyr/</loc>
   </url>
   <url>
      <loc>http://spark.rstudio.com/mlib/</loc>
   </url>
   <url>
      <loc>http://spark.rstudio.com/guides/distributed-r/</loc>
   </url>
   <url>
      <loc>http://spark.rstudio.com/guides/pipelines/</loc>
   </url>
</urlset> 
```

Notice that titles are missing on each article, they are currently set to `<title></title>` so maybe rename to the article title? That should create a nice landing page like...

<img width="631" alt="screen shot 2018-06-13 at 9 58 49 am" src="https://user-images.githubusercontent.com/3478847/41340933-69160fbe-6ef0-11e8-9e05-9f5f7c62ef59.png">

**Comment by edgararuiz** [comment]
<img width="691" alt="Screen Shot 2022-04-28 at 10 05 59 AM" src="https://user-images.githubusercontent.com/77294576/165783841-c3922b7f-1330-44eb-821e-f634b0a34045.png">
