### ISSUE TITLE
YARN master specification in deployment page

### ISSUE THREAD

**Issue by MarcinKosinski** [rstudio/spark.rstudio.com#8]
It is 

``` R
library(sparklyr)
sc <- spark_connect(master = "yarn-client")
```

here https://github.com/rstudio/spark.rstudio.com/blob/master/deployment.Rmd

but this works for spark version 1.6.1 .

Should there be a note that in spark 2.0.0 you should specify master as `yarn` for YARN clusters, and provide additional parameter to config? `--deployMode="client"` ?

**Comment by jjallaire** [comment]
@nwstephens Could you make this change?

**Comment by MarcinKosinski** [comment]
Outdated
